version: '3'

services:
  web:
    build: .
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - '.:/usr/local/apache2/htdocs/'

  script_fetch_weather:
    build:
      context: .
      dockerfile: Dockerfileweather
    
    volumes:
      - '.:/home'
    
volumes:
  storage: